org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djdk.net.unixdomain.tmpdir=D:/young/work/leapauto/.gradle-tmp
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.java.home=C:\\Program Files\\Microsoft\\jdk-17.0.20.101-hotspot
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
